- docs/ADR-35-coms-protocol-optimizations.md
Please checkout the Communication protocol optimizations
> ADR-35: Communication protocol optimizations

- docs/ADR-40-ui-dependencies-upgrades.md
This PR adds the ADR for the UI dependencies upgrades. A change that will impact apps that use DCL UI as a dependencies.
> feat: Add the UI dependencies upgrades ADR

- docs/ADR-47-collections-secondary-marketplaces-v2.md
- docs/ADR-48-locking-collections-in-the-builder.md
Closes https://github.com/decentraland/builder-server/issues/361
> feat: lock collection adr

- README.md
- docs/ADR-50-isolated-scenes.md
This is the ADR 50 regarding the isolated mode
> feat: adr 50

- README.md
- docs/ADR-54-oracle-for-mana-pricing.md
Created ADR for mana prices being calculated according to MANA/USD rate instead of a fixed amount of MANA
> feat: ADR-54 oracle for MANA prices

- README.md
- docs/ADR-59-user-store-catalyst-entity.md
ADR for the Store Entity.
Contains the schema and an explanation of all properties.
Also a way on how to fetch a store from the catalyst and an example of the payload.
> feat: ADR-59 Store entity

- docs/ADR-57-avatar-assembling-for-visualization.md
Expanded ADR 57 with info on tinting materials for avatar
> chore: added material tinting to the avatar assembling ADR57

- docs/ADR-72-ethereum-api-provider.md
Read docs with flows: https://github.com/decentraland/adr/blob/feat/provider-handler/docs/ADR-72-ethereum-api-provider.md
> feat: add ADR-72 ethereum api handler

- docs/ADR-42-third-party-assets-integration.md
I think we also need to specify what happens when invalid data is supplied to the server/endpoint. To that end, I added what we're currently doing on the [third party resolver example repo](https://github.com/decentraland/third-party-api-resolver-example) but we might want to specify a particular HTTP error.
> feat: add bloom filter endpoint

- docs/ADR-70-new-comms.md
Old comms endpoints will be added to the new version of the protocol.
> docs: ADR-70 Amendment

- ADR/ADR-85-profile-pictures.md
Add implementation details to ADR-85.
> chore: ADR-85 include implementation details

- content/ADR-133-scene-runtime.md
Implementation https://github.com/decentraland/scene-runtime/pull/48
> ADR-133: adapt scene runtime to CommonJS

- content/ADR-137-new-friend-request.md
Signed-off-by: Nicolas Lorusso <56365551+lorux0@users.noreply.github.com>
> cancel friend request changes and replaced GetFriendRequestsV2 & AddFriendRequestsV2

- content/ADR-144.md
closes #144
Signed-off-by: menduz <github@menduz.com>
> ADR-144 Realm resolution from connection string

- content/ADR-137-new-friend-request.md
New Friend Request feature. Find more info about the proposal [here](https://www.notion.so/decentraland/PRD-New-Friend-Requests-188555225272448f91f3eea5e84f1cd3).
> feat: update msg to follow new definitions

- content/ADR-153.md
> ADR-153 - Semantics of entity parenting with ECS-compatible semantics

- content/ADR-151.md
closes #151 - this ADR was written by an AI
Signed-off-by: menduz <github@menduz.com>
> ADR-151 - Rendering order for UI entities

- content/ADR-76-urn-prefix-search.md
fixes https://github.com/decentraland/catalyst/issues/1366
> Fix ADR to reflect the reality

- content/ADR-159-subgraph-cloudflare-worker.md
- content/ADR-170-subgraph-cloudflare-worker.md
ADR-170 for the subgraph cloudflare worker
> feat: ADR-170 subgraph worker

- content/ADR-117-CRDT-protocol.md
https://github.com/decentraland/adr/pull/169 and https://github.com/decentraland/adr/pull/168 should converge in this one (which currently is a draft one)
> Revision v2 for ADR 117 (CRDTs)

- README.md
Signed-off-by: frami <i@2fd.me>
> fix: readme link to ADR-1

- content/ADR-239-avatar-assembly-changes.md
- content/ADR-57-avatar-assembling-for-visualization.md
Based on issue #239 this is the ADR about the avatar assembly definition changes
> ADR 239 - Avatar assembly definition

- content/ADR-244-extended-minted-items-addressable.md
Adds details about the modified endpoints.
> docs: updates ADR-244 to detail how Catalyst endpoints will change

- content/ADR-244-extended-minted-items-addressable.md
Remove endpoint that won't change from the changes list.
> fix: remove endpoint that won't change

- content/ADR-74-add-emote-schema.md
Add new properties to emote metadata that will identify if the emote has sound or geometry included in the entity.
This will be needed to identify and filter emotes correctly from the marketplace
> feat: add sound and geometry to emote metadata

- content/ADR-133-scene-runtime.md
This is already exposed in https://github.com/decentraland/js-sdk-toolchain/blob/main/packages/%40dcl/js-runtime/index.d.ts
> ADR-133: add websocket and fetch details

- content/ADR-244-extended-minted-items-addressable.md
This reverts commit 2f5087194dcf196563478366b1d37a37c550ccd5.
> Revert "feat: mark ADR-244 as Living (#257)"

- content/ADR-280-binaries-creator-hub.md
Binary Management in Creators Hub
> ADR-280: binary management in creator hub

- content/ADR-281-items.md
> ADR-281: items in decentraland tooling

- content/ADR-282-inspector.md
> ADR-282: Decentraland Inspector

- content/ADR-282-inspector.md
Fix data layer types, local data layer definition was mixed with in-memory file system interface
> ADR-282: Fix data layer types
